### ISSUE TITLE
Setup CI pipeline

### ISSUE THREAD

**Issue by AshciR** [rick1e/group-chat-digest#20]
Ideally we want a continuous integration pipeline for this project. It will ensure code quality and facilitate automatic deployments.

Suggestions:
 - Use GitHub Actions

**Comment by AshciR** [comment]
```
name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Set to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest /tests

```
